services:
  postgres:
    image: docker.io/library/postgres:16-alpine
    container_name: pipeline_postgres
    environment:
      POSTGRES_USER: pipeline_admin
      POSTGRES_PASSWORD: pipeline_password
      POSTGRES_DB: pipeline
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: